// Real-browser regression checks for the public build. CI supplies pinned Playwright.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve('dist-pages');
const server=http.createServer((req,res)=>{
  const file=path.resolve(root,'.'+(req.url==='/'?'/index.html':req.url.split('?')[0]));
  if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}
  try{res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}
});
(async()=>{
 await new Promise(r=>server.listen(4185,'127.0.0.1',r));
 let browser;
 try{
  browser=await chromium.launch({channel:'chrome',headless:true,args:['--no-sandbox']});
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  page.setDefaultTimeout(30000);
  console.log('Browser opened');
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',message=>{if(message.text().startsWith('Audio export:'))console.log(message.text());});
  await page.addInitScript(()=>{
    const render=OfflineAudioContext.prototype.startRendering;
    OfflineAudioContext.prototype.startRendering=function(){const start=performance.now();console.log('Audio export: native render started');return render.call(this).then(buffer=>{console.log('Audio export: native render finished in '+Math.round(performance.now()-start)+'ms');return buffer;});};
    const click=HTMLAnchorElement.prototype.click;
    HTMLAnchorElement.prototype.click=function(){if(this.download)console.log('Audio export: download requested '+this.download);return click.call(this);};
  });
  await page.goto('http://127.0.0.1:4185/');
  await page.getByRole('button',{name:/^Play track 1:/}).waitFor();
  assert.equal(await page.locator('#track-editor').count(),0);
  assert.equal(await page.locator('#generation-settings').count(),0);
  await page.getByRole('button',{name:'Create 3 tracks',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.take-card').length===3);
  const cards=page.locator('.take-card');
  assert.equal(await page.locator('.score-section').count(),5);
  assert.ok((await page.locator('.score-progress').innerText()).includes('Release'));
  await cards.nth(0).getByRole('button',{name:/^Play track/}).click();
  await cards.nth(0).getByRole('button',{name:/^Stop track/}).waitFor();
  await cards.nth(1).getByRole('button',{name:/^Play track/}).click();
  await cards.nth(1).getByRole('button',{name:/^Stop track/}).waitFor();
  assert.equal(await page.getByRole('button',{name:/^Stop track/}).count(),1);
  assert.ok((await cards.nth(1).getAttribute('class')).includes('selected'));
  await page.getByRole('button',{name:'Stop playback',exact:true}).click();
  await cards.nth(1).getByRole('button',{name:/^Play track/}).waitFor();
  await cards.nth(0).getByRole('button',{name:'Customize track 1',exact:true}).click();
  await page.getByRole('textbox',{name:'Song title',exact:true}).fill('Saved edit while comparing');
  await page.getByRole('combobox',{name:'Pattern bar',exact:true}).click();
  await page.getByRole('option',{name:'Bar 12 · Peak',exact:true}).click();
  assert.ok((await page.locator('.phrase-controls').innerText()).includes('bar 12 · Peak'));
  const note=page.getByRole('button',{name:/^Melody step 1:/}),before=await note.getAttribute('aria-label');
  await note.click();assert.notEqual(await note.getAttribute('aria-label'),before);
  await cards.nth(1).getByRole('button',{name:/^Play track/}).click();
  await cards.nth(0).getByRole('button',{name:/^Play track/}).click();
  assert.equal(await page.getByRole('textbox',{name:'Song title',exact:true}).inputValue(),'Saved edit while comparing');
  await page.getByRole('button',{name:'Stop playback',exact:true}).click();
  await page.getByRole('switch',{name:'Studio mode',exact:true}).click();
  assert.equal(await page.locator('#generation-settings').count(),1);
  assert.equal(await page.locator('#track-editor').count(),1);
  await page.getByRole('switch',{name:'Studio mode',exact:true}).click();
  await page.getByRole('button',{name:/Customize this track/}).click();
  assert.equal(await page.locator('#track-editor').count(),0);
  assert.equal(await page.locator('#generation-settings').count(),0);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile page must not overflow horizontally');
  await cards.nth(2).getByRole('button',{name:/^Play track/}).click();
  await cards.nth(2).getByRole('button',{name:/^Stop track/}).waitFor();
  await cards.nth(2).getByRole('button',{name:/^Stop track/}).click();
  // Related generations retain the favorite alongside new takes.
  await cards.nth(0).getByRole('button',{name:'More like track 1',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.take-card').length===4);
  assert.ok((await cards.nth(0).innerText()).includes('Saved edit while comparing'));
  await page.waitForFunction(()=>{
    const data=JSON.parse(localStorage.getItem('pss:recent:v1')||'null');
    return data?.batches.find(b=>b.id===data.activeId)?.takes.length===4;
  });
  await page.reload();
  await page.waitForFunction(()=>document.querySelectorAll('.take-card').length===4);
  await page.getByRole('button',{name:'Create 3 tracks',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.take-card').length===3);
  await page.getByRole('button',{name:/^Recent \(/}).click();
  await page.getByRole('dialog').getByRole('button').filter({hasText:'More like:'}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.take-card').length===4);
  assert.ok((await cards.nth(0).innerText()).includes('Saved edit while comparing'));
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.getByRole('button',{name:'Customize track 1',exact:true}).click();
  await page.getByRole('combobox',{name:'Song length',exact:true}).click();
  await page.getByRole('option',{name:'32 bars',exact:true}).click();
  assert.equal(await page.locator('.score-section small').allTextContents().then(a=>a.reduce((n,x)=>n+parseInt(x),0)),32);
  console.log('Base studio checks passed');
  // Expansion always targets the clicked take, and cancellation preserves the session.
  const source=await page.evaluate(()=>JSON.parse(localStorage.getItem('pss:session:v1')));
  const secondTitle=await cards.nth(1).locator('.take-details strong').innerText();
  await page.getByRole('button',{name:'Expand track 2 into full song',exact:true}).click();
  assert.ok((await page.getByRole('dialog').innerText()).includes(secondTitle));
  await page.getByRole('combobox',{name:'Full song duration',exact:true}).click();
  await page.getByRole('option',{name:'Custom',exact:true}).click();
  await page.getByRole('spinbutton',{name:'Duration in seconds (120–300)',exact:true}).fill('119');
  assert.equal(await page.getByRole('button',{name:'Create full song',exact:true}).isDisabled(),true);
  await page.getByRole('spinbutton',{name:'Duration in seconds (120–300)',exact:true}).fill('150');
  assert.equal(await page.getByRole('button',{name:'Create full song',exact:true}).isEnabled(),true);
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('pss:session:v1'))),source);
  console.log('Expansion dialog and cancellation passed');
  // Two-minute expansion keeps the original beside a separately selected full song.
  await page.getByRole('button',{name:'Expand track 1 into full song',exact:true}).click();
  await page.getByRole('button',{name:'Create full song',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.take-card').length===2);
  assert.equal(await page.locator('.score-section').count(),8);
  assert.equal(await page.getByRole('switch',{name:'Loop',exact:true}).getAttribute('aria-checked'),'false');
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('pss:session:v1'))?.arrangement?.plan.version===2);
  const pair=await page.evaluate(()=>{const r=JSON.parse(localStorage.getItem('pss:recent:v1'));return r.batches.find(b=>b.id===r.activeId).takes;});
  assert.deepEqual(pair[0],source);assert.notEqual(pair[1].id,source.id);assert.equal(pair[1].arrangement.plan.targetSeconds,120);
  assert.ok(pair[1].bars*240/pair[1].bpm>=120);
  await cards.nth(1).getByRole('button',{name:/^Play track/}).click();
  await cards.nth(1).getByRole('button',{name:/^Stop track/}).waitFor();
  await page.getByRole('button',{name:'Stop playback',exact:true}).click();
  console.log('Two-minute expansion passed');
  // Generate three minutes from the same favorite, then restore/save/export the result.
  await page.getByRole('button',{name:'Expand track 1 into full song',exact:true}).click();
  await page.getByRole('combobox',{name:'Full song duration',exact:true}).click();
  await page.getByRole('option',{name:'3 minutes',exact:true}).click();
  await page.getByRole('button',{name:'Create full song',exact:true}).click();
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('pss:session:v1'))?.arrangement?.plan.targetSeconds===180);
  const expanded=await page.evaluate(()=>JSON.parse(localStorage.getItem('pss:session:v1')));
  await page.reload();
  await page.waitForFunction(()=>document.querySelectorAll('.take-card').length===2);
  assert.equal(await page.locator('.score-section').count(),8);
  assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('pss:session:v1'))),expanded);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Expanded song must fit mobile width');
  await page.getByRole('button',{name:'Save track 2',exact:true}).click();
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('pss:songs:v1')).some(s=>s.arrangement?.plan.targetSeconds===180));
  await page.setViewportSize({width:1440,height:1000});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  console.log('Three-minute expansion and reload passed');
  // Render native Web Audio to a WAV file, not just a mock audio graph.
  await page.getByRole('button',{name:'Export',exact:true}).click();
  const jsonPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Download song JSON',exact:true}).click();
  const jsonDownload=await jsonPromise;assert.deepEqual(JSON.parse(fs.readFileSync(await jsonDownload.path(),'utf8')),expanded);
  const downloadPromise=page.waitForEvent('download',{timeout:90000}).catch(async error=>{console.error('Export state:',await page.locator('body').innerText());throw error;});
  console.log('Starting full-song WAV render');
  await page.getByRole('button',{name:'Download WAV',exact:true}).click();
  const download=await downloadPromise;console.log('WAV download complete');const wav=fs.readFileSync(await download.path());
  assert.equal(wav.subarray(0,4).toString(),'RIFF');assert.equal(wav.readUInt16LE(22),2);assert.equal(wav.length,44+Math.ceil((expanded.bars*240/expanded.bpm+2)*44100)*4);
  assert.ok(wav.some((v,i)=>i>=44&&v!==0),'Native full-song render must contain audio');
  await page.locator('input[type=file]').setInputFiles(await jsonDownload.path());
  await page.getByText('Song imported.',{exact:true}).waitFor();
  assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('pss:session:v1'))),expanded);
  assert.deepEqual(errors,[]);
  console.log('Browser checks passed: default simplicity, direct playback, switching, bottom-player sync, edit retention, Studio mode, desktop/mobile fit, expansion/cancel/durations, original retention, full-song storage, JSON round trip, and native three-minute WAV.');
 }finally{if(browser)await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
