'use client';
import { useCallback, useEffect, useRef, useState, type CSSProperties } from 'react';
import { flushSync } from 'react-dom';
import { AudioLines, Play, Square, Sparkles, Shuffle, Download, Save, FolderOpen, Upload, Undo2, Volume2, VolumeX, Headphones, ArrowUpRight, SlidersHorizontal, CircleHelp, Music2, X, LoaderCircle } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { TRACKS, NOTES, GENRES, SCALES, EXAMPLES, compose, composeBatch, moreLike, validateSong, remix, chordName, duration, patternForBar, editPatternStep, type Song, type Track } from '@/lib/song';
import { interpretPrompt } from '@/lib/interpret';
import { THEMES } from '@/lib/themes';
import { buildScore, expandSong, withoutScore } from '@/lib/score';
import { fullSongBars } from '@/lib/plan';
import { RECENT_KEY, readRecent, upsertRecent, type RecentBatch } from '@/lib/recent';
import { Player, renderWav, saveFile, type Progress } from '@/lib/audio';

const INITIAL=compose(EXAMPLES[0].prompt,{seed:1827});
const COLORS:Record<Track,string>={kick:'#e6f89d',snare:'#edb880',hat:'#80d2c7',bass:'#8ab7ec',lead:'#c6a0ff',pad:'#e298b9'};
const LABELS:Record<Track,string>={kick:'Kick',snare:'Snare',hat:'Hi-hat',bass:'Bass',lead:'Melody',pad:'Chords'};
const EMPTY_PROGRESS={step:-1,bar:0,elapsed:0};
const randomSeed=()=>crypto.getRandomValues(new Uint32Array(1))[0];
const formatTime=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
const fileName=(s:Song)=>s.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'my-song';
function Choice({label,value,items,onChange}:{label:string;value:string;items:readonly string[];onChange:(v:string)=>void}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i} value={i}>{i}</SelectItem>)}</SelectContent></Select>;}
function Range({label,value,min=0,max=100,step=1,onChange,suffix=''}:{label:string;value:number;min?:number;max?:number;step?:number;onChange:(v:number)=>void;suffix?:string}){return <div className="range-field"><div className="field-label"><span>{label}</span><span className="mono">{Math.round(value)}{suffix}</span></div><Slider aria-label={label} value={[value]} min={min} max={max} step={step} onValueChange={v=>onChange(v[0])}/></div>;}
function Scope({player,playing,song}:{player:React.RefObject<Player|null>;playing:boolean;song:Song}){
  const canvas=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{let frame=0;const el=canvas.current;if(!el)return;const ctx=el.getContext('2d');if(!ctx)return;const draw=()=>{const w=el.clientWidth,h=el.clientHeight,dpr=Math.min(window.devicePixelRatio||1,2);if(el.width!==w*dpr||el.height!==h*dpr){el.width=w*dpr;el.height=h*dpr;}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const bins=64,values=new Uint8Array(128);const analyser=player.current?.synth?.analyser;if(playing&&analyser)analyser.getByteFrequencyData(values);const gap=3,bw=w/bins-gap;for(let i=0;i<bins;i++){let v=values[i]/255;if(!playing){const step=i%16;v=TRACKS.reduce((sum,t)=>sum+(song.muted[t]?0:(patternForBar(song,Math.floor(i/16))[t][step]>=(t==='bass'||t==='lead'?0:.01)?song.mix[t]:0)),0)/7;v*=.6+Math.sin(i*1.71)**2*.4;}const bar=Math.max(3,v*(h-8));ctx.fillStyle=playing?'#dcf995':i%4===0?'#809c59':'#435638';ctx.fillRect(i*(bw+gap),h/2-bar/2,bw,bar);}if(playing)frame=requestAnimationFrame(draw);};draw();return ()=>cancelAnimationFrame(frame);},[playing,song,player]);
  return <canvas ref={canvas} className="scope" role="img" aria-label={playing?'Live audio frequency spectrum':'Pattern activity preview'}/>;
}
export default function Studio(){
  const [editBar,setEditBar]=useState(0);
  const [expandSource,setExpandSource]=useState<Song|null>(null),[expandLength,setExpandLength]=useState('2 minutes'),[customSeconds,setCustomSeconds]=useState('150');
  const expandSeconds=expandLength==='Custom'?Number(customSeconds):expandLength==='3 minutes'?180:120;
  const validExpansion=Number.isInteger(expandSeconds)&&expandSeconds>=120&&expandSeconds<=300;
  const expandedDuration=expandSource&&validExpansion?fullSongBars(expandSource.bpm,expandSeconds)*240/expandSource.bpm:0;
  const [generationForm,setGenerationForm]=useState('Evolving score'),[scoreLength,setScoreLength]=useState('16 bars');
  const [recent,setRecent]=useState<RecentBatch[]>([]),[activeBatch,setActiveBatch]=useState<RecentBatch|null>(null),[recentOpen,setRecentOpen]=useState(false);
  const [studioMode,setStudioMode]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[customizeOpen,setCustomizeOpen]=useState(false);
  const resultsRef=useRef<HTMLElement>(null);
  const [generationCount,setGenerationCount]=useState(3),[takes,setTakes]=useState<Song[]>([]);
  const [song,setSong]=useState<Song>(INITIAL),[prompt,setPrompt]=useState(EXAMPLES[0].prompt),[genre,setGenre]=useState('Auto'),[energyOverride,setEnergyOverride]=useState<number|undefined>();
  const [playing,setPlaying]=useState(false),[starting,setStarting]=useState(false),[progress,setProgress]=useState<Progress>(EMPTY_PROGRESS),[loop,setLoop]=useState(true),[volume,setVolume]=useState(65);
  const [songs,setSongs]=useState<Song[]>([]),[ready,setReady]=useState(false),[libraryOpen,setLibraryOpen]=useState(false),[helpOpen,setHelpOpen]=useState(false),[exportOpen,setExportOpen]=useState(false),[tail,setTail]=useState(true),[exporting,setExporting]=useState(false),[undoCount,setUndoCount]=useState(0);
  const nextPlan=interpretPrompt(prompt,{genre,energy:energyOverride});
  const energy=Math.round(nextPlan.energy*100);
  const history=useRef<Song[]>([]),player=useRef<Player|null>(null),fileInput=useRef<HTMLInputElement>(null),latest=useRef(song),playOperation=useRef(0),storageWarned=useRef(false);
  latest.current=song;
  const stop=useCallback(()=>{playOperation.current++;player.current?.stop();setPlaying(false);setStarting(false);setProgress(EMPTY_PROGRESS);},[]);
  const apply=useCallback((next:Song,record=true)=>{const safe=validateSong(next),current=latest.current;stop();setEditBar(b=>Math.min(b,safe.arrangement?safe.bars-1:3));setTakes(previous=>previous.map(t=>t.id===current.id?current:t));if(record){history.current=[...history.current.slice(-19),latest.current];setUndoCount(history.current.length);}latest.current=safe;setSong(safe);},[stop]);
  useEffect(()=>{player.current=new Player();try{const stored=localStorage.getItem('pss:session:v1');if(stored){const s=validateSong(JSON.parse(stored));latest.current=s;setSong(s);setLoop(!s.arrangement);setPrompt(s.prompt);}const library=JSON.parse(localStorage.getItem('pss:songs:v1')||'[]');if(Array.isArray(library))setSongs(library.slice(0,50).flatMap(item=>{try{return [validateSong(item)];}catch{return [];}}));}catch{toast.info('Your last session could not be restored. A fresh song is ready.');}let restored:ReturnType<typeof readRecent>={batches:[],activeId:''};try{restored=readRecent(localStorage.getItem(RECENT_KEY));}catch{}setRecent(restored.batches);const active=restored.batches.find(b=>b.id===restored.activeId);if(active){setActiveBatch(active);setTakes(active.takes);}setReady(true);return ()=>player.current?.stop();},[]);
  useEffect(()=>{if(!ready)return;try{localStorage.setItem('pss:session:v1',JSON.stringify(song));}catch{if(!storageWarned.current){toast.warning('Browser storage is unavailable. Export JSON to keep your song.');storageWarned.current=true;}}},[song,ready]);
  useEffect(()=>{if(!ready||!activeBatch)return;const updated={...activeBatch,takes:takes.map(t=>t.id===song.id?song:t)};setRecent(previous=>upsertRecent(previous,updated));},[song,takes,activeBatch,ready]);
  useEffect(()=>{if(!ready)return;try{localStorage.setItem(RECENT_KEY,JSON.stringify({version:1,activeId:activeBatch?.id||'',batches:recent}));}catch{if(!storageWarned.current){toast.warning('Recent generations could not be saved. Export favorites as JSON.');storageWarned.current=true;}}},[recent,activeBatch,ready]);
  useEffect(()=>{if(player.current){player.current.loop=loop;player.current.setMix(song,volume/100);}},[song,volume,loop]);
  const startSong=useCallback(async(target:Song)=>{if(!player.current)return;const operation=++playOperation.current;setStarting(true);setPlaying(false);setProgress(EMPTY_PROGRESS);try{player.current.loop=loop;player.current.volume=volume/100;await player.current.start(target,p=>{if(operation===playOperation.current)setProgress(p);},()=>{if(operation===playOperation.current){setPlaying(false);setProgress(EMPTY_PROGRESS);}});if(operation===playOperation.current)setPlaying(player.current.playing);}catch(e){if(operation===playOperation.current)toast.error(e instanceof Error?e.message:'Playback could not start.');}finally{if(operation===playOperation.current)setStarting(false);}},[loop,volume]);
  const togglePlay=useCallback(async()=>{if(playing||starting){stop();return;}await startSong(latest.current);},[playing,starting,stop,startSong]);
  const playTake=(take:Song)=>{if(take.id===latest.current.id){void togglePlay();return;}setEditBar(0);apply(take);void startSong(latest.current);};
  const selectTake=(take:Song)=>{if(take.id!==latest.current.id){setEditBar(0);apply(take);}};

  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{const el=e.target as HTMLElement;if(e.code==='Space'&&!['INPUT','TEXTAREA','BUTTON','SELECT'].includes(el.tagName)&&!el.isContentEditable&&!el.closest('[role="dialog"],[role="slider"],[role="combobox"],[role="switch"],[role="tab"]')){e.preventDefault();void togglePlay();}};window.addEventListener('keydown',onKey);return ()=>window.removeEventListener('keydown',onKey);},[togglePlay]);
  const generate=useCallback((text=prompt,selected=genre,resetOverrides=false)=>{try{const batch=composeBatch(text,generationCount,{genre:selected,energy:resetOverrides?undefined:energyOverride,seed:randomSeed(),form:generationForm==='Evolving score'?'score':'loop',length:parseInt(scoreLength) as 16|32});if(resetOverrides){setEnergyOverride(undefined);setGenre('Auto');}setLoop(!batch[0].arrangement);setEditBar(0);apply(batch[0]);setTakes(batch);setActiveBatch({id:`batch-${randomSeed()}`,createdAt:Date.now(),label:text,takes:batch});setPrompt(text);requestAnimationFrame(()=>{resultsRef.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});resultsRef.current?.focus({preventScroll:true});});toast.success(batch.length===1?'Your new track is ready. Press play.':`${batch.length} tracks ready. Press Play on any track to compare.`);return batch[0];}catch(e){toast.error((e as Error).message);return null;}},[prompt,genre,energyOverride,apply,generationCount,generationForm,scoreLength]);
  const makeSimilar=(source:Song)=>{try{const variations=moreLike(source,generationCount,randomSeed()),batch=[source,...variations];apply(source);setTakes(batch);setActiveBatch({id:`batch-${randomSeed()}`,createdAt:Date.now(),label:`More like: ${source.title}`,takes:batch});setEditBar(0);toast.success(`Original kept, plus ${variations.length} related takes.`);}catch(e){toast.error((e as Error).message);}};
  const makeFullSong=()=>{if(!expandSource||!validExpansion)return;try{const full=expandSong(expandSource,expandSeconds,`full-${randomSeed()}`),batch=[expandSource,full];apply(full);setTakes(batch);setActiveBatch({id:`batch-${randomSeed()}`,createdAt:Date.now(),label:`Expanded: ${expandSource.title}`,takes:batch});setLoop(false);setEditBar(0);setExpandSource(null);toast.success('Full song ready. Your original is beside it.');requestAnimationFrame(()=>{resultsRef.current?.scrollIntoView({behavior:'smooth',block:'start'});resultsRef.current?.focus({preventScroll:true});});}catch(e){toast.error((e as Error).message);}};
  const restoreBatch=(batch:RecentBatch)=>{apply(batch.takes[0]);setLoop(!batch.takes[0].arrangement);setTakes(batch.takes);setActiveBatch(batch);setPrompt(batch.takes[0].prompt);setGenre('Auto');setEnergyOverride(undefined);setRecentOpen(false);setEditBar(0);toast.success('Recent generation restored.');};
  const loadTheme=(id:string)=>{const theme=THEMES.find(t=>t.id===id);if(!theme)return;setPrompt(theme.prompt);setGenre('Auto');setEnergyOverride(undefined);toast(`${theme.name} loaded. Tweak it or create a track.`);};
  const randomizeTheme=()=>{const choices=THEMES.filter(t=>t.prompt!==prompt);loadTheme(choices[randomSeed()%choices.length].id);};
  const saveSong=(target:Song=song)=>{const snapshot=validateSong({...target,id:`saved-${randomSeed()}`});const next=[snapshot,...songs].slice(0,50);try{localStorage.setItem('pss:songs:v1',JSON.stringify(next));setSongs(next);toast.success('Saved to My songs on this device.');}catch{toast.error('Storage is full or unavailable. Export a JSON file instead.');}};
  const undo=()=>{const previous=history.current.pop();if(previous){apply(previous,false);setUndoCount(history.current.length);toast('Last edit undone.');}};
  const update=(partial:Partial<Song>)=>apply({...song,...partial});
  const visibleBar=song.arrangement?(playing?progress.bar:Math.min(editBar,song.bars-1)):song.composerVersion===2?(playing?progress.bar%4:Math.min(editBar,3)):0;
  const barChoices=song.arrangement?song.arrangement.bars.map((b,i)=>`Bar ${i+1} · ${b.role}`):['Bar A','Bar B','Bar C','Bar D'];
  const chordOffset=song.arrangement?Math.floor(visibleBar/4)*4:0;
  const visiblePattern=patternForBar(song,visibleBar);
  const editStep=(track:Track,i:number)=>{const old=visiblePattern[track][i],melodic=track==='bass'||track==='lead';const value=melodic?(old<0?0:old<2?2:old<4?4:old<7?7:-1):old>0?0:track==='pad'?1:.8;setEditBar(visibleBar);apply(editPatternStep(song,visibleBar,track,i,value));};
  const mute=(track:Track)=>setSong(s=>({...s,muted:{...s.muted,[track]:!s.muted[track]}}));
  const importSong=async(file?:File)=>{if(!file)return;try{if(file.size>500000)throw new Error('Choose a song JSON file smaller than 500 KB.');const s=validateSong(JSON.parse(await file.text()));apply(s);setPrompt(s.prompt);toast.success('Song imported.');}catch(e){toast.error(e instanceof SyntaxError?'That file is not valid JSON.':(e as Error).message);}finally{if(fileInput.current)fileInput.current.value='';}};
  const exportAudio=async()=>{setExporting(true);try{await new Promise(r=>setTimeout(r,30));const blob=await renderWav(song,volume/100,tail);saveFile(blob,`${fileName(song)}.wav`);toast.success('WAV ready. Check your browser downloads.');setExportOpen(false);}catch{toast.error('Audio export failed. Try a shorter track or another browser.');}finally{setExporting(false);}};
  const actions=useRef({apply,generate,stop});actions.current={apply,generate,stop};
  useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'get_song',description:'Read the current instrumental song, its settings and patterns.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>structuredClone(latest.current)},{name:'compose_song',description:'Replace the current song with a new instrumental composition from a prompt. Does not start playback.',inputSchema:{type:'object',properties:{prompt:{type:'string',minLength:1,maxLength:2000},genre:{type:'string',enum:['Auto',...GENRES]}},required:['prompt'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(input:unknown)=>{const args=input as {prompt?:unknown;genre?:unknown};if(!args||typeof args.prompt!=='string'||!args.prompt.trim()||args.prompt.length>2000||(args.genre!==undefined&&!(typeof args.genre==='string'&&['Auto',...GENRES].includes(args.genre))))throw new Error('Provide a prompt and an optional supported genre.');const s=compose(args.prompt,{genre:args.genre as string|undefined,seed:randomSeed()});flushSync(()=>{actions.current.apply(s);setPrompt(s.prompt);setGenre(typeof args.genre==='string'?args.genre:'Auto');setEnergyOverride(undefined);});return {title:s.title,bpm:s.bpm,genre:s.genre,status:'ready'};}},{name:'stop_playback',description:'Stop music playback.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:()=>{flushSync(()=>actions.current.stop());return {playing:false};}}];for(const tool of tools){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}return ()=>lifecycle.abort();},[]);
  const savedCurrent=songs.some(s=>JSON.stringify({...s,id:''})===JSON.stringify({...song,id:''}));
  const visibleTakes=takes.some(t=>t.id===song.id)?takes.map(t=>t.id===song.id?song:t):[song,...takes];
  return <div className="studio-shell simple-studio"><Toaster theme="dark" position="top-center"/>
    <header className="topbar"><a className="brand" href="./" aria-label="Prompt Song Studio home"><span className="brand-icon"><AudioLines size={24}/></span><span>prompt<span className="brand-light">song</span><span className="brand-sub">STUDIO</span></span></a><div className="top-note"><span className="demo-pill">DEMO 10</span><span>Your ideas. In full sound.</span></div><div className="top-actions"><div className="studio-mode"><Switch id="studio-mode" checked={studioMode} onCheckedChange={setStudioMode}/><label htmlFor="studio-mode">Studio mode</label></div><button className="button ghost" onClick={()=>setLibraryOpen(true)}><FolderOpen size={17}/><span>My songs</span><span className="count">{songs.length}</span></button><button className="icon-button" aria-label="How the studio works" onClick={()=>setHelpOpen(true)}><CircleHelp size={19}/></button></div></header>
    <main className="workspace">
      <section className="compose-panel" aria-labelledby="describe-heading"><div className="eyebrow"><span className="number">01</span> DESCRIBE</div><h1 id="describe-heading">What does your <em>world sound like?</em></h1><p className="intro">Describe a scene. Create a few options. Find your sound.</p><div className="theme-picker"><div className="theme-heading"><label id="theme-label">20 worlds to explore</label><button className="button subtle" onClick={randomizeTheme}><Shuffle size={16}/>Randomize</button></div><Select value={THEMES.find(t=>t.prompt===prompt)?.id||''} onValueChange={loadTheme}><SelectTrigger aria-labelledby="theme-label" className="theme-select"><SelectValue placeholder="Choose a theme…"/></SelectTrigger><SelectContent>{THEMES.map(theme=><SelectItem key={theme.id} value={theme.id}>{theme.name}</SelectItem>)}</SelectContent></Select></div><label className="sr-only" htmlFor="music-prompt">Describe your music</label><div className="prompt-box"><textarea id="music-prompt" value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={2000} placeholder="A dungeon crawler enters a boss fight. Upbeat, fast, and intense…"/><div className="prompt-bottom"><AudioLines size={16}/><span>Describe the scene, mood, and pace</span><span>{prompt.length}/2000</span></div></div>
        <button className="disclosure-button" aria-expanded={studioMode||settingsOpen} aria-controls="generation-settings" onClick={()=>setSettingsOpen(v=>!v)} disabled={studioMode}><SlidersHorizontal size={16}/>Music settings <span>{studioMode||settingsOpen?'Hide':'Optional'}</span></button>
        {(studioMode||settingsOpen)&&<div id="generation-settings" className="generation-settings"><div className="setting-row"><label>Structure</label><Choice label="Generation structure" value={generationForm} items={['Evolving score','Loop']} onChange={setGenerationForm}/></div>{generationForm==='Evolving score'&&<div className="setting-row"><label>Score length</label><Choice label="Score length" value={scoreLength} items={['16 bars','32 bars']} onChange={setScoreLength}/></div>}<p className="section-hint">For your next generation. Specify a tempo or key in the description, such as “128 BPM in F major.”</p>        {prompt.trim()&&<div className="interpretation-card"><div className="interpretation-heading"><Sparkles size={14}/><span>Interpreted as · next track</span></div><div className="interpretation-tags"><span>{nextPlan.label}</span><span>{nextPlan.mood}</span><span>{nextPlan.pace} · {nextPlan.bpm} BPM</span><span>{Math.round(nextPlan.energy*100)}% energy</span><span>{nextPlan.genre}</span></div>{nextPlan.evidence.length>0&&<p>From: {nextPlan.evidence.map(x=>`“${x}”`).join(', ')}</p>}{nextPlan.notes.map(note=><p className="interpretation-note" key={note}>{note}</p>)}<small>Interprets the action and mood; it doesn’t know characters or book plots.</small></div>}
        <div className="setting-row"><label>Style</label><Choice label="Music style" value={genre} items={['Auto',...GENRES]} onChange={setGenre}/></div>
        <Range label="Energy" value={energy} onChange={v=>setEnergyOverride(v/100)}/><div className="energy-mode"><span>{energyOverride===undefined?'Following your description':'Manual energy override'}</span>{energyOverride!==undefined&&<button className="text-button" onClick={()=>setEnergyOverride(undefined)}>Use description</button>}</div><div className="range-ends"><span>Laid-back</span><span>All in</span></div>
</div>}
        <div className="generate-row"><span className="eyebrow"><span className="number">02</span> GENERATE</span>        <div className="setting-row"><label>How many tracks?</label><Choice label="Number of tracks to generate" value={String(generationCount)} items={['1','2','3','4','5']} onChange={v=>setGenerationCount(Number(v))}/></div><button className="button primary generate" onClick={()=>generate()} disabled={!prompt.trim()}><Sparkles size={18}/>{generationCount===1?'Create a track':`Create ${generationCount} tracks`}<ArrowUpRight size={18}/></button></div>
      </section>
      <section ref={resultsRef} tabIndex={-1} className="track-panel" aria-label="Your tracks"><div className="results-heading"><div><div className="eyebrow"><span className="number">03</span> LISTEN</div><h2>Your tracks</h2></div><p role="status">{takes.length?`${takes.length} tracks ready. Press Play to compare.`:'A sample is ready to try. Or create your own above.'}</p><button className="button subtle" onClick={()=>setRecentOpen(true)}>Recent ({recent.length})</button></div>
        <div className="take-list">{visibleTakes.map((take,i)=>{const active=take.id===song.id,busy=active&&starting,audible=active&&playing;return <article key={take.id} className={`take-card ${active?'selected':''}`} aria-label={`Track ${i+1}: ${take.title}`}><span className="take-number">{i+1}</span><div className="take-details"><strong>{take.title}</strong><small>{(activeBatch?.label.startsWith('More like:')||activeBatch?.label.startsWith('Expanded:'))&&i===0?'Original · ':''}{take.direction&&<><span className="direction-badge">{take.direction}</span> · </>}{take.arrangement?.plan.version===2?'Full song':take.arrangement?'Score':'Loop'} · {take.genre} · {formatTime(duration(take))} · {take.bpm} BPM{audible?' · Playing':active?' · Selected':''}</small></div><div className="take-actions"><button className="button primary take-play" disabled={!ready} onClick={()=>playTake(take)} aria-label={`${busy||audible?'Stop':'Play'} track ${i+1}: ${take.title}`}>{busy?<LoaderCircle size={16} className="spin"/>:audible?<Square size={16}/>:<Play size={16}/>} {busy?'Cancel':audible?'Stop':'Play'}</button><button className="button subtle expand-track" onClick={()=>{stop();setExpandLength('2 minutes');setExpandSource(structuredClone(take));}} aria-label={`Expand track ${i+1} into full song`}><AudioLines size={16}/><span>Expand into full song</span></button><button className="button subtle" onClick={()=>makeSimilar(take)} aria-label={`More like track ${i+1}`}><Sparkles size={16}/><span>More like this</span></button><button className="button subtle" onClick={()=>saveSong(take)} aria-label={`Save track ${i+1}`}><Save size={16}/><span>Save</span></button><button className="button subtle" onClick={()=>{selectTake(take);setCustomizeOpen(true);requestAnimationFrame(()=>document.getElementById('customize-section')?.scrollIntoView({behavior:'smooth',block:'start'}));}} aria-label={`Customize track ${i+1}`}><SlidersHorizontal size={16}/><span>Customize</span></button></div></article>;})}</div>
        {song.arrangement&&<div className={`score-progress ${song.arrangement.plan.version===2?'full-score':''}`} aria-label="Score sections">{song.arrangement.plan.sections.map((section,i)=>{const start=song.arrangement!.plan.sections.slice(0,i).reduce((n,x)=>n+x.bars,0),active=progress.bar>=start&&progress.bar<start+section.bars;return <div className={playing&&active?'score-section active':'score-section'} style={{flex:section.bars}} key={section.role}><strong>{section.role}</strong><small>{section.bars} bars</small></div>;})}</div>}
        <p className="takes-note">Your last 12 batches stay in Recent on this browser. Save or export favorites to keep them longer.</p>
        <div id="customize-section"><button className="disclosure-button customize-toggle" aria-expanded={studioMode||customizeOpen} aria-controls="track-editor" onClick={()=>setCustomizeOpen(v=>!v)} disabled={studioMode}><SlidersHorizontal size={17}/>Customize this track <span>{studioMode||customizeOpen?'Open':'Optional'}</span></button><p className="section-hint">{song.title} · changes apply to this track</p>
        {(studioMode||customizeOpen)&&<div id="track-editor"><div className="track-top"><div className="eyebrow">MAKE IT YOURS</div><div className="track-actions"><button className="icon-button" disabled={!undoCount} onClick={undo} aria-label="Undo last edit"><Undo2 size={17}/></button><button className="button subtle" onClick={()=>{apply(remix(song,randomSeed()));toast.success('New variation ready.');}}><Shuffle size={16}/>Remix</button><button className="button subtle" onClick={()=>saveSong()}><Save size={16}/>Save</button></div></div>
        {!song.interpretation&&<div className="composer-update"><span>Scene descriptions now shape the music. Your saved pattern is unchanged.</span><button className="text-button" onClick={()=>generate(song.prompt||song.genre,'Auto',true)}>Recreate this prompt<Shuffle size={14}/></button></div>}
        <div className="track-title"><div><input className="title-input" aria-label="Song title" maxLength={80} value={song.title} onChange={e=>setSong(s=>({...s,title:e.target.value}))} onBlur={()=>{if(!song.title.trim())setSong(s=>({...s,title:'Untitled loop'}));}}/><div className="song-meta"><span>{song.genre}</span><span>{NOTES[song.root]} {song.scale}</span><span>{song.bpm} BPM</span><span>{formatTime(duration(song))}</span></div></div><span className="ready-label">{playing?'PLAYING':savedCurrent?'SAVED':'READY TO PLAY'}</span></div>
        <div className="sound-display"><div className="scope-header"><span>{playing?'LIVE SPECTRUM':'PATTERN OVERVIEW'}</span><span className="mono">{String(progress.bar+1).padStart(2,'0')} / {String(song.bars).padStart(2,'0')} BARS</span></div><Scope player={player} playing={playing} song={song}/><div className="chord-strip">{song.chords.map((_,i)=><div className={playing&&progress.bar%4===i?'chord active':'chord'} key={i}><span className="chord-index">0{i+1}</span><strong>{chordName(song,chordOffset+i)}</strong><span>{playing&&progress.bar%4===i?<AudioLines size={15}/>:<span className="chord-line"/>}</span></div>)}</div></div>
        <Tabs defaultValue="sequence" className="editor-tabs"><div className="editor-header"><TabsList variant="line"><TabsTrigger value="sequence"><AudioLines size={16}/>Sequencer</TabsTrigger><TabsTrigger value="mix"><SlidersHorizontal size={16}/>Sound & mix</TabsTrigger></TabsList><span className="editor-note">{playing?'Mix live · pattern edits stop playback':'Make it your own'}</span></div>
          <TabsContent value="sequence">{(song.composerVersion===2||song.arrangement)&&<div className="phrase-controls"><span>{playing?'Playing':'Edit'} {song.arrangement?`bar ${visibleBar+1} · ${song.arrangement.bars[visibleBar].role}`:`bar ${String.fromCharCode(65+visibleBar)} · loop phrase`}</span><Choice label="Pattern bar" value={barChoices[visibleBar]} items={barChoices} onChange={v=>{stop();setEditBar(barChoices.indexOf(v));}}/></div>}<div className="sequencer-scroll"><div className="sequencer"><div className="sequence-ruler"><span>INSTRUMENT</span>{Array.from({length:16},(_,i)=><span key={i}>{i%4===0?i/4+1:'·'}</span>)}</div>{TRACKS.map(track=><div className={`sequence-row ${song.muted[track]?'muted':''}`} style={{'--track':COLORS[track]} as CSSProperties} key={track}><button className="track-label" onClick={()=>mute(track)} aria-pressed={!song.muted[track]} aria-label={`${song.muted[track]?'Unmute':'Mute'} ${LABELS[track]}`}><span className="track-dot"/><span>{LABELS[track]}</span>{song.muted[track]?<VolumeX size={13}/>:<Volume2 size={13}/>}</button>{visiblePattern[track].map((value,i)=>{const on=track==='bass'||track==='lead'?value>=0:value>0;return <button key={i} className={`step ${on?'on':''} ${i%4===0?'beat-start':''} ${playing&&progress.step===i?'current':''}`} onClick={()=>editStep(track,i)} aria-label={`${LABELS[track]} step ${i+1}: ${on?'on'+(track==='bass'||track==='lead'?`, degree ${value+1}`:''):'off'}`} aria-pressed={on}>{on&&(track==='bass'||track==='lead')?<span>{value+1}</span>:on&&track==='pad'?<span>≡</span>:null}</button>;})}</div>)}</div></div><p className="sequence-tip">Tap a step to edit this bar. Melody steps cycle through notes; tap an instrument to mute it.</p></TabsContent>
          <TabsContent value="mix"><div className="mix-grid">{TRACKS.map(track=><div className="mixer-channel" key={track} style={{'--track':COLORS[track]} as CSSProperties}><div className="field-label"><button onClick={()=>mute(track)} className="mix-label" aria-label={`${song.muted[track]?'Unmute':'Mute'} ${LABELS[track]}`}><span className="track-dot"/>{LABELS[track]}{song.muted[track]?<VolumeX size={14}/>:null}</button><span className="mono">{Math.round(song.mix[track]*100)}%</span></div><Slider aria-label={`${LABELS[track]} volume`} min={0} max={100} value={[song.mix[track]*100]} onValueChange={v=>setSong(s=>({...s,mix:{...s.mix,[track]:v[0]/100}}))}/></div>)}</div><div className="sound-choices"><div><label>Bass tone</label><Choice label="Bass tone" value={song.sound.bass} items={['round','acid','sub']} onChange={v=>update({sound:{...song.sound,bass:v as Song['sound']['bass']}})}/></div><div><label>Melody tone</label><Choice label="Melody tone" value={song.sound.lead} items={['pluck','bell','square','keys','sine','supersaw','reed','mallet','strings']} onChange={v=>update({sound:{...song.sound,lead:v as Song['sound']['lead']}})}/></div><div><label>Chord tone</label><Choice label="Chord tone" value={song.sound.pad} items={['warm','glass','keys']} onChange={v=>update({sound:{...song.sound,pad:v as Song['sound']['pad']}})}/></div></div><div className="fx-row"><Range label="Reverb" value={song.sound.reverb*100} max={60} suffix="%" onChange={v=>update({sound:{...song.sound,reverb:v/100}})}/><Range label="Delay" value={song.sound.delay*100} max={50} suffix="%" onChange={v=>update({sound:{...song.sound,delay:v/100}})}/></div></TabsContent>
        </Tabs>
        <p className="section-hint">{song.arrangement?.plan.version===2?'Full song length follows its tempo. Expand again for another duration; changing structure rebuilds the sections.':'Changing score length rebuilds its sections from the base phrase.'} Undo restores your bar edits.</p><div className="setting-row"><label>Track structure</label><Choice label="Current track structure" value={song.arrangement?'Evolving score':'Loop'} items={['Evolving score','Loop']} onChange={v=>{setLoop(v==='Loop');setEditBar(0);apply(v==='Loop'?withoutScore(song):buildScore(song,16));}}/></div><div className="track-settings"><div className="tempo-setting"><Range label="Tempo" value={song.bpm} min={55} max={180} suffix=" BPM" onChange={v=>update({bpm:v})}/></div><div><label>Key</label><Choice label="Root note" value={NOTES[song.root]} items={NOTES} onChange={v=>update({root:NOTES.indexOf(v)})}/></div><div><label>Scale</label><Choice label="Scale" value={song.scale} items={Object.keys(SCALES)} onChange={v=>update({scale:v as Song['scale']})}/></div><div><label>Length</label>{song.arrangement?.plan.version===2?<span className="full-song-length">{formatTime(duration(song))} · {song.bars} bars</span>:<Choice label="Song length" value={`${song.bars} bars`} items={song.arrangement?['16 bars','32 bars']:['4 bars','8 bars','16 bars']} onChange={v=>{setEditBar(0);apply(song.arrangement?buildScore(song,parseInt(v) as 16|32):{...song,bars:parseInt(v)});}}/>}</div></div>
        </div>}</div>
        <div className="track-footer"><div><span className="small-badge">INSTRUMENTAL</span><span>Six voices. Endless possibilities.</span></div><button className="text-button" onClick={()=>fileInput.current?.click()}><Upload size={15}/>Import song</button><input ref={fileInput} hidden type="file" accept=".json,application/json" onChange={e=>void importSong(e.target.files?.[0])}/></div>
      </section>
    </main>
    <footer className="transport"><div className="now-playing"><span className={`album-icon ${playing?'is-playing':''}`}><AudioLines size={24}/></span><div><strong>{song.title}</strong><span>{playing?'Playing in your browser':starting?'Starting audio…':'Ready when you are'}</span></div></div><div className="playback-controls"><button className="play-button" onClick={()=>void togglePlay()} aria-label={playing||starting?'Stop playback':'Play song'} disabled={!ready}>{starting?<LoaderCircle size={21} className="spin"/>:playing?<Square size={18} fill="currentColor"/>:<Play size={21} fill="currentColor"/>}</button><span className="transport-time mono">{formatTime(progress.elapsed)}<span> / {formatTime(duration(song))}</span></span><div className="loop-control"><Switch id="loop-playback" checked={loop} onCheckedChange={setLoop}/><label htmlFor="loop-playback">Loop</label></div></div><div className="output-controls"><div className="master-volume"><Volume2 size={18}/><Slider aria-label="Master volume" value={[volume]} max={100} onValueChange={v=>setVolume(v[0])}/></div><button className="button export" onClick={()=>setExportOpen(true)}><Download size={17}/><span>Export</span></button></div></footer>
    <Dialog open={!!expandSource} onOpenChange={open=>{if(!open)setExpandSource(null);}}><DialogContent className="expand-dialog"><DialogHeader><DialogTitle>Expand into a full song</DialogTitle><DialogDescription>Develop “{expandSource?.title}” into a longer instrumental. Your original stays beside the new version.</DialogDescription></DialogHeader><div className="setting-row"><label>Target length</label><Choice label="Full song duration" value={expandLength} items={['2 minutes','3 minutes','Custom']} onChange={setExpandLength}/></div>{expandLength==='Custom'&&<div className="custom-duration"><label htmlFor="full-song-seconds">Duration in seconds (120–300)</label><input id="full-song-seconds" type="number" min={120} max={300} step={1} value={customSeconds} onChange={e=>setCustomSeconds(e.target.value)} aria-invalid={!validExpansion} aria-describedby="expansion-preview"/></div>}<p id="expansion-preview" className="expansion-preview" role="status">{validExpansion?`About ${formatTime(Math.ceil(expandedDuration))} at ${expandSource?.bpm} BPM. Ends on a complete phrase.`:'Enter a whole number from 120 to 300 seconds.'}</p><p className="section-hint">Keeps your theme, tempo, key, instruments, and mix. Adds a variation, build, peak, breakdown, final return, and ending.</p><div className="expand-actions"><button className="button secondary" onClick={()=>setExpandSource(null)}>Cancel</button><button className="button primary" disabled={!validExpansion} onClick={makeFullSong}><AudioLines size={17}/>Create full song</button></div></DialogContent></Dialog>
    <Dialog open={recentOpen} onOpenChange={setRecentOpen}><DialogContent className="library-dialog"><DialogHeader><DialogTitle>Recent generations</DialogTitle><DialogDescription>Your last 12 batches, stored on this browser. Restore a batch to compare or refine it.</DialogDescription></DialogHeader>{recent.length===0?<p>Create a batch to start your history.</p>:<div className="saved-list">{recent.map(batch=><div className="saved-song" key={batch.id}><button onClick={()=>restoreBatch(batch)}><Music2 size={20}/><span><strong>{batch.label}</strong><small>{batch.takes.length} tracks · {new Date(batch.createdAt).toLocaleString()}</small></span><span>Restore</span></button></div>)}</div>}</DialogContent></Dialog>
    <Dialog open={libraryOpen} onOpenChange={setLibraryOpen}><DialogContent className="library-dialog"><DialogHeader><DialogTitle>My songs <span className="muted-text">({songs.length})</span></DialogTitle><DialogDescription>Saved on this device. Export JSON to keep a portable backup.</DialogDescription></DialogHeader>{!songs.length?<div className="empty-songs"><FolderOpen size={32}/><h3>Keep a good idea.</h3><p>Save a track and it will be waiting here.</p></div>:<div className="saved-list">{songs.map((s,i)=><div className="saved-song" key={s.id}><button onClick={()=>{apply(s);setPrompt(s.prompt);setLibraryOpen(false);}}><Music2 size={20}/><span><strong>{s.title}</strong><small>{s.genre} · {s.bpm} BPM · {NOTES[s.root]} {s.scale}</small></span><ArrowUpRight size={17}/></button><button className="icon-button" aria-label={`Remove ${s.title}`} onClick={()=>{const previous=songs,next=songs.filter((_,j)=>j!==i);try{localStorage.setItem('pss:songs:v1',JSON.stringify(next));setSongs(next);toast('Song removed.',{action:{label:'Undo',onClick:()=>{try{localStorage.setItem('pss:songs:v1',JSON.stringify(previous));setSongs(previous);}catch{toast.error('Could not restore saved song.');}}}});}catch{toast.error('Could not update saved songs.');}}}><X size={16}/></button></div>)}</div>}</DialogContent></Dialog>
    <Dialog open={helpOpen} onOpenChange={setHelpOpen}><DialogContent><DialogHeader><DialogTitle>From a thought to a track.</DialogTitle><DialogDescription>Prompt Song Studio · Demo 10</DialogDescription></DialogHeader><div className="help-content"><p><strong>1. Describe it.</strong> Choose one of 20 themes or tap Randomize for a different idea, then choose 1–5 tracks to generate. Loading a theme resets style and energy to follow its description. You can also write your own prompt, such as “house, 128 BPM, F major, acid bass,” or edit a theme description. Describe an action, mood, and pace: “a boss fight with upbeat, fast music.” New track names use details from your description; you can edit the title directly. The interpretation preview shows the scene, style, energy, and tempo for the next track. Explicit BPM and key requests take priority; choosing a style or moving the energy slider overrides automatic choices. This is a local rule-based interpreter, with no book knowledge or connected AI model.</p><p><strong>2. Make it yours.</strong> Press Play directly on any track to compare. Music settings affect the next generation; Customize this track opens the sequencer, mix, and effects for the selected track. Studio mode keeps both sections open. Switching keeps each take’s edits for this session; Recent keeps your last 12 batches across reloads; save favorites to keep them longer. Press play, remix the groove, edit individual score bars or the four-bar loop phrase, or balance the six voices. Mix and mute controls work live; other edits stop playback so you can restart with the new sound.</p><p><strong>3. Keep the result.</strong> Save on this device, download stereo WAV audio, or export a song JSON file you can import later. Evolving scores develop through five sections. Expand into full song keeps the original alongside a new 2–5 minute arrangement with a variation, breakdown, and final return. The actual duration rounds up to a two-bar phrase. Expansion reuses the accepted theme and its edits; Save or export favorites to keep them beyond Recent. Reed, mallet, and strings are synthesized tones; vocals and recorded samples are not included.</p><p className="help-tip">Desktop shortcut: <kbd>Space</kbd> to play or stop. On your phone, tap Play and keep the page open. If audio is quiet, check your media volume and output device.</p></div></DialogContent></Dialog>
    <Dialog open={exportOpen} onOpenChange={v=>{if(!exporting)setExportOpen(v);}}><DialogContent><DialogHeader><DialogTitle>Take your track with you.</DialogTitle><DialogDescription>{song.title} · {formatTime(duration(song))} · {song.bpm} BPM</DialogDescription></DialogHeader><div className="export-option"><div className="export-option-title"><AudioLines size={25}/><div><h3>Stereo WAV</h3><p>44.1 kHz · 16-bit · includes your mix</p></div></div><div className="field-label"><label htmlFor="export-tail">Include a 2-second effect tail</label><Switch id="export-tail" checked={tail} onCheckedChange={setTail} disabled={exporting}/></div><p className="muted-text">Turn off for an exact-length loop. Reverb starts fresh on each rendered file.</p><button className="button primary" disabled={exporting} onClick={()=>void exportAudio()}>{exporting?<LoaderCircle size={17} className="spin"/>:<Download size={17}/>} {exporting?'Rendering your audio…':'Download WAV'}</button></div><button className="button secondary" disabled={exporting} onClick={()=>{saveFile(new Blob([JSON.stringify(song,null,2)],{type:'application/json'}),`${fileName(song)}.json`);toast.success('Song JSON exported.');}}><Download size={17}/>Download song JSON</button></DialogContent></Dialog>
  </div>;
}
